# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_receitas', '0002_auto_20171017_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
