# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_receitas', '0003_usuario_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescricaoReceita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=100)),
                ('nome_receita', models.CharField(max_length=100)),
                ('descrição_receita', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('porcoes', models.IntegerField()),
                ('calorias', models.IntegerField()),
                ('tempo_preparo', models.TimeField()),
                ('preparo', models.CharField(max_length=500)),
                ('coximento', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ingrediente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('unidade', models.CharField(max_length=20)),
                ('fk_descricaoReceita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_receitas.DescricaoReceita')),
                ('fk_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_receitas.Ingrediente')),
            ],
        ),
    ]
