# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_receitas', '0004_descricaoreceita_ingrediente_receita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='static/images')),
            ],
        ),
        migrations.RemoveField(
            model_name='receita',
            name='fk_descricaoReceita',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='fk_ingrediente',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='unidade',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='fk_receita_ingrediente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='site_receitas.Receita'),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='unidade',
            field=models.CharField(default='su', max_length=50),
        ),
        migrations.AddField(
            model_name='receita',
            name='autor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('d', 'Doce'), ('s', 'Salgado'), ('b', 'Bebidas')], default='SC', max_length=1),
        ),
        migrations.AddField(
            model_name='receita',
            name='descricao',
            field=models.TextField(max_length=300, null=True, verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='receita',
            name='instrucoes_preparo',
            field=models.TextField(max_length=800, null=True, verbose_name='instruções de preparo'),
        ),
        migrations.AddField(
            model_name='receita',
            name='metodo_cozimento',
            field=models.CharField(max_length=100, null=True, verbose_name='método de cozimento'),
        ),
        migrations.AddField(
            model_name='receita',
            name='nome_receita',
            field=models.CharField(max_length=50, null=True, verbose_name='nome da receita'),
        ),
        migrations.AddField(
            model_name='receita',
            name='procoes',
            field=models.PositiveIntegerField(default=0, verbose_name='porções'),
        ),
        migrations.AddField(
            model_name='receita',
            name='tempo_preparo',
            field=models.PositiveIntegerField(default=0, verbose_name='tempo de preparo'),
        ),
        migrations.AddField(
            model_name='receita',
            name='val_nutricional',
            field=models.PositiveIntegerField(default=0, verbose_name='valor nutricional'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nome_ingrediente',
            field=models.CharField(max_length=50, verbose_name='ingrediente'),
        ),
        migrations.DeleteModel(
            name='DescricaoReceita',
        ),
        migrations.AddField(
            model_name='imagem',
            name='fk_receita_imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_receitas.Receita'),
        ),
    ]
