# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_receitas', '0005_auto_20171117_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='fk_receita_imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='site_receitas.Receita'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='imagem',
            field=models.ImageField(upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='fk_receita_ingrediente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='site_receitas.Receita'),
        ),
    ]
