# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 02:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_receitas', '0008_auto_20171121_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.TextField(max_length=1000, verbose_name='Comentario')),
                ('fk_receita_comentario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='site_receitas.Receita')),
                ('fk_usuario_comentario', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fk_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
